name: Deploy using workflow dispatch in test branch

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy to test
        run: echo "Deploying test"
